### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by SuNflOw1991** [LunaTTvBot/LunaBot#44]
Implement a chat where the streamer could interact with the chat in his or the bots name.
It would be nice to have a chat that can be popped out so that a tab change would not hide the chat again.

**Comment by CapCalamity** [comment]
I think this is already implemented.
#92 implements a chat with which the streamer can chat with the audience.  
The 'Start' tab can also be pulled out from the main-view.

Do we have anything else or can we close this Issue?

**Comment by iPaat** [comment]
I think for now we could close that. But the 'chat' needs a general overhaul later. E.g. using MVVM Pattern and so on.
